_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [248.78, 248.66, 248.60]
  PIXEL_STD: [30.47, 30.78, 30.91]
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("DCU_train",)
  TEST: ("DCU_val",)
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 6
  CHECKPOINT_PERIOD: 5000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 100000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  RANDOM_FLIP: "none"
  HFLIP_TRAIN: false
  CROP:
    ENABLED: false
    SIZE: [0.5, 0.95]



