_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "solov2_v0.0.0.pth"
  PIXEL_MEAN: [248.78, 248.66, 248.60]
  PIXEL_STD: [30.47, 30.78, 30.91]
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("DCU_train",)
  TEST: ("DCU_val",)
TEST:
  EVAL_PERIOD: 1000
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 2000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.00025
  STEPS: (3000, 5000)
  MAX_ITER: 5000
INPUT:
  RANDOM_FLIP: "none"


