_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "solov2_baseline.pth"
  PIXEL_MEAN: [248.78, 248.66, 248.60]
  PIXEL_STD: [30.47, 30.78, 30.91]
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("DCU_train",)
  TEST: ("DCU_val",)
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 5000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.01
  STEPS: (80000, 90000)
  MAX_ITER: 100000
INPUT:
  MIN_SIZE_TRAIN: (416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928)
  RANDOM_FLIP: "none"
  HFLIP_TRAIN: false
  CROP:
    ENABLED: false
    SIZE: [0.5, 0.95]